server:
  port: 8081
---
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 6000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms

---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true